// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmipiycbzzsunsfdutaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtaXBpeWNienpzdW5zZmR1dGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTk0MjQsImV4cCI6MjA3MDU5NTQyNH0.q7J9RyI8--u5m8px2JB5qsjMV4XmuNWI0P7SbjjHQJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});